### PR TITLE
docs: added development guide to the readme

### PR DESCRIPTION
**Pull request by LOLdevelopr**
This is PR for the **Development Guide** for the docs. Reference to https://github.com/masterwendu/babybet/issues/13

### CODE REVIEW

**Comment by masterwendu** [comment]
Hey @LOLdevelopr 

Thanks for your help. Really good start to come to a better documentation.

You write that yarn workspace is in use. But it isn't. Actually I heard the first time now from it. Would you be so kind and create workspace package.json for the project?

**Comment by LOLdevelopr** [comment]
Ohh i saw yarn and monorepo and thought its using workspace 😅
Yeah I will submit a new PR for that. Cause I am also not sure of that either. Like never had to setup that... I used it in a workspace defined setup. Will give it a shot.

**Comment by masterwendu** [comment]
> Ohh i saw yarn and monorepo and thought its using workspace 
> Yeah I will submit a new PR for that. Cause I am also not sure of that either. Like never had to setup that... I used it in a workspace defined setup. Will give it a shot.

OK thanks. I assume you will do a second MR for Hacktoberfest?

Then I will merge this for now :clap:

**Comment by LOLdevelopr** [comment]
Yeah mostly. I will do that ASAP 🙂

**Pull request merged**
